### ISSUE TITLE
Curve click error

### ISSUE THREAD

**Issue by ryust** [sarweshkumar47/Curve-Fit#6]
Got this error trying to click a curve after an app sleep/resume... maybe also related to the weak references issues...

    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
        at com.makesense.labs.curvefit.impl.CurveManager$DelegatingCurveClickListener.onPolylineClick(CurveManager.java:142)
        at com.google.android.gms.maps.zzq.zza(Unknown Source:2)
        at com.google.android.gms.maps.internal.zzbg.dispatchTransaction(Unknown Source:5)
        at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:12)
        at android.os.Binder.transact(Binder.java:667)
        at hl.b(:com.google.android.gms.dynamite_mapsdynamite@18381081@18.3.81 (100400-257258062):14)
        at com.google.android.gms.maps.internal.bu.a(:com.google.android.gms.dynamite_mapsdynamite@18381081@18.3.81 (100400-257258062):4)
        at com.google.maps.api.android.lib6.impl.dt.y(:com.google.android.gms.dynamite_mapsdynamite@18381081@18.3.81 (100400-257258062):270)
        at com.google.maps.api.android.lib6.gmm6.api.r.a(:com.google.android.gms.dynamite_mapsdynamite@18381081@18.3.81 (100400-257258062):137)
        at com.google.maps.api.android.lib6.gmm6.api.q.a(:com.google.android.gms.dynamite_mapsdynamite@18381081@18.3.81 (100400-257258062):58)
        at com.google.maps.api.android.lib6.gmm6.vector.af.b(:com.google.android.gms.dynamite_mapsdynamite@18381081@18.3.81 (100400-257258062):130)
        at com.google.maps.api.android.lib6.gmm6.vector.dc.onSingleTapConfirmed(:com.google.android.gms.dynamite_mapsdynamite@18381081@18.3.81 (100400-257258062):22)
        at com.google.maps.api.android.lib6.impl.gesture.c.onSingleTapConfirmed(:com.google.android.gms.dynamite_mapsdynamite@18381081@18.3.81 (100400-257258062):240)
        at com.google.maps.api.android.lib6.impl.gesture.e.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@18381081@18.3.81 (100400-257258062):9)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by sarweshkumar47** [comment]
Yes. It is related to WeakReferences. 

This bug has been fixed in new 2.0.0 beta version. Please try using that.

**Comment by ryust** [comment]
I can't implement the Android Maps beta yet... any way you can add the fix to the current 1.1.0 release for those of us that need to run without the beta?

**Comment by sarweshkumar47** [comment]
Sorry for late reply. I was on leave due to medical emergency. I will add the fix to the non beta version soon.

**Comment by sarweshkumar47** [comment]
The patch is applied. [Curve-Fit 1.1.1](https://github.com/sarweshkumar47/Curve-Fit/releases/tag/version_1_1_1) is available now.
